#!/usr/bin/env python3
"""Generate tag usage statistics from Hugo content front matter."""

from __future__ import annotations

import ast
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTENT_DIR = ROOT / "content"
GLOSSARY_PATH = ROOT / "docs" / "tags-glossary.md"
REPORT_PATH = ROOT / "docs" / "tags-stats.generated.md"


@dataclass(frozen=True)
class Article:
    path: Path
    title: str
    category: str
    section: str
    tags: tuple[str, ...]


def front_matter(text: str) -> str:
    if not text.startswith("---\n"):
        return ""
    end = text.find("\n---", 4)
    if end == -1:
        return ""
    return text[4:end]


def front_matter_value(front: str, key: str) -> str:
    match = re.search(rf"^{re.escape(key)}:\s*(.*)$", front, re.MULTILINE)
    return match.group(1).strip() if match else ""


def parse_tags(raw: str, path: Path) -> tuple[str, ...]:
    if not raw:
        return ()
    if any(ch in raw for ch in "“”‘’"):
        raise ValueError(f"{path}: tags use curly quotes: {raw}")
    try:
        parsed = ast.literal_eval(raw)
    except (SyntaxError, ValueError) as exc:
        raise ValueError(f"{path}: cannot parse tags: {raw}") from exc
    if not isinstance(parsed, list) or not all(isinstance(tag, str) for tag in parsed):
        raise ValueError(f"{path}: tags must be a list of strings")
    return tuple(parsed)


def load_articles() -> list[Article]:
    articles: list[Article] = []
    for path in sorted(CONTENT_DIR.glob("post*/**/*.md")):
        text = path.read_text(encoding="utf-8")
        front = front_matter(text)
        tags = parse_tags(front_matter_value(front, "tags"), path.relative_to(ROOT))
        articles.append(
            Article(
                path=path.relative_to(ROOT),
                title=front_matter_value(front, "title").strip("'\""),
                category=front_matter_value(front, "categories"),
                section=path.relative_to(CONTENT_DIR).parts[0],
                tags=tags,
            )
        )
    return articles


def load_glossary_tags() -> set[str]:
    if not GLOSSARY_PATH.exists():
        return set()
    text = GLOSSARY_PATH.read_text(encoding="utf-8")
    return set(re.findall(r"^### `(.+?)`", text, re.MULTILINE))


def bucket_label(count: int) -> str:
    if count <= 3:
        return str(count)
    if count <= 5:
        return "4-5"
    if count <= 10:
        return "6-10"
    if count <= 20:
        return "11-20"
    if count <= 50:
        return "21-50"
    if count <= 100:
        return "51-100"
    return "101+"


def md_table(headers: list[str], rows: list[list[str]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return lines


def article_link(article: Article) -> str:
    return f"`{article.path}`"


def generate_report(articles: list[Article], glossary_tags: set[str]) -> str:
    tag_usage: Counter[str] = Counter()
    tag_categories: dict[str, Counter[str]] = defaultdict(Counter)
    tag_articles: dict[str, list[Article]] = defaultdict(list)
    article_tag_counts: Counter[int] = Counter()

    for article in articles:
        article_tag_counts[len(article.tags)] += 1
        for tag in article.tags:
            tag_usage[tag] += 1
            tag_categories[tag][article.category or article.section] += 1
            tag_articles[tag].append(article)

    unique_tags = set(tag_usage)
    buckets: Counter[str] = Counter(bucket_label(count) for count in tag_usage.values())
    bucket_order = ["1", "2", "3", "4-5", "6-10", "11-20", "21-50", "51-100", "101+"]

    missing_from_glossary = sorted(unique_tags - glossary_tags)
    unused_in_content = sorted(glossary_tags - unique_tags)

    lines: list[str] = [
        "# Tags Stats",
        "",
        "> This file is generated by `scripts/generate_tags_report.py`. Do not edit it manually.",
        "",
        "## Summary",
        "",
    ]
    total_assignments = sum(tag_usage.values())
    average = total_assignments / len(articles) if articles else 0
    lines.extend(
        [
            f"- Articles scanned: {len(articles)}",
            f"- Articles with tags: {sum(1 for article in articles if article.tags)}",
            f"- Unique tags: {len(unique_tags)}",
            f"- Total tag assignments: {total_assignments}",
            f"- Average tags per article: {average:.2f}",
            f"- Glossary tags: {len(glossary_tags)}",
            f"- Used tags missing from glossary: {len(missing_from_glossary)}",
            f"- Glossary tags unused in content: {len(unused_in_content)}",
            "",
            "## Usage Buckets",
            "",
        ]
    )
    lines.extend(
        md_table(
            ["Articles per tag", "Unique tag count"],
            [[label, str(buckets.get(label, 0))] for label in bucket_order],
        )
    )

    lines.extend(["", "## Tags Per Article", ""])
    lines.extend(
        md_table(
            ["Tags on article", "Article count"],
            [[str(count), str(article_tag_counts[count])] for count in sorted(article_tag_counts)],
        )
    )

    lines.extend(["", "## Top Tags", ""])
    top_rows = []
    for tag, count in tag_usage.most_common(50):
        categories = ", ".join(
            f"{category}: {category_count}"
            for category, category_count in tag_categories[tag].most_common(4)
        )
        top_rows.append([f"`{tag}`", str(count), categories])
    lines.extend(md_table(["Tag", "Uses", "Top categories"], top_rows))

    lines.extend(["", "## Single-use Tags", ""])
    single_rows = []
    for tag in sorted(tag for tag, count in tag_usage.items() if count == 1):
        article = tag_articles[tag][0]
        single_rows.append([f"`{tag}`", article_link(article), article.title])
    lines.extend(md_table(["Tag", "Article", "Title"], single_rows))

    lines.extend(["", "## Glossary Audit", ""])
    if missing_from_glossary:
        lines.extend(["### Used tags missing from glossary", ""])
        lines.extend("- `" + tag + "`" for tag in missing_from_glossary)
        lines.append("")
    else:
        lines.extend(["### Used tags missing from glossary", "", "None.", ""])

    if unused_in_content:
        lines.extend(["### Glossary tags unused in content", ""])
        lines.extend("- `" + tag + "`" for tag in unused_in_content)
        lines.append("")
    else:
        lines.extend(["### Glossary tags unused in content", "", "None.", ""])

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    articles = load_articles()
    glossary_tags = load_glossary_tags()
    REPORT_PATH.write_text(generate_report(articles, glossary_tags), encoding="utf-8")
    print(f"Generated {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
